require("busted_setup")

describe("codex.config", function()
  local config

  before_each(function()
    package.loaded["codex.config"] = nil
    config = require("codex.config")
  end)

  describe("defaults", function()
    it("has codex_cmd = 'codex'", function()
      assert.equals("codex", config.defaults.codex_cmd)
    end)
    it("has auto_start = true", function()
      assert.is_true(config.defaults.auto_start)
    end)
    it("has terminal.provider = 'auto'", function()
      assert.equals("auto", config.defaults.terminal.provider)
    end)
    it("has terminal.split_side = 'right'", function()
      assert.equals("right", config.defaults.terminal.split_side)
    end)
    it("has terminal.split_width_percentage = 0.30", function()
      assert.equals(0.30, config.defaults.terminal.split_width_percentage)
    end)
    it("has approval.policy = 'prompt'", function()
      assert.equals("prompt", config.defaults.approval.policy)
    end)
    it("has approval.sandbox = 'workspace-write'", function()
      assert.equals("workspace-write", config.defaults.approval.sandbox)
    end)
    it("has queue_timeout = 5000", function()
      assert.equals(5000, config.defaults.queue_timeout)
    end)
  end)

  describe("apply()", function()
    it("returns defaults when called with empty table", function()
      local cfg = config.apply({})
      assert.equals("codex", cfg.codex_cmd)
      assert.equals("right", cfg.terminal.split_side)
      assert.equals("auto", cfg.terminal.provider)
    end)
    it("overrides top-level string key", function()
      local cfg = config.apply({ codex_cmd = "codex2" })
      assert.equals("codex2", cfg.codex_cmd)
    end)
    it("overrides top-level boolean key", function()
      local cfg = config.apply({ auto_start = false })
      assert.is_false(cfg.auto_start)
    end)
    it("deep merges terminal subtable preserving other keys", function()
      local cfg = config.apply({ terminal = { provider = "native" } })
      assert.equals("native", cfg.terminal.provider)
      assert.equals("right", cfg.terminal.split_side)
      assert.equals(0.30, cfg.terminal.split_width_percentage)
    end)
    it("deep merges approval subtable preserving other keys", function()
      local cfg = config.apply({ approval = { policy = "auto-allow" } })
      assert.equals("auto-allow", cfg.approval.policy)
      assert.equals("workspace-write", cfg.approval.sandbox)
    end)
    it("does NOT mutate defaults on deep merge", function()
      config.apply({ terminal = { provider = "native" } })
      assert.equals("auto", config.defaults.terminal.provider)
    end)
    it("handles nil user_config gracefully", function()
      local cfg = config.apply(nil)
      assert.equals("codex", cfg.codex_cmd)
    end)
  end)

  describe("validate()", function()
    it("passes for fully valid config", function()
      assert.has_no.errors(function()
        config.validate(config.apply({}))
      end)
    end)
    it("errors on invalid terminal.provider", function()
      local ok, err = pcall(config.validate, { terminal = { provider = "bad_provider" } })
      assert.is_false(ok)
      assert.is_truthy(err:find("terminal%.provider"))
    end)
    it("errors on invalid approval.policy", function()
      local ok, err = pcall(config.validate, { approval = { policy = "bad" } })
      assert.is_false(ok)
      assert.is_truthy(err:find("approval%.policy"))
    end)
    it("errors on non-string codex_cmd", function()
      local ok, err = pcall(config.validate, { codex_cmd = 42 })
      assert.is_false(ok)
      assert.is_truthy(err:find("codex_cmd"))
    end)
    it("accepts all valid terminal providers", function()
      for _, p in ipairs({ "auto", "snacks", "native", "external", "none" }) do
        assert.has_no.errors(function()
          config.validate({ terminal = { provider = p } })
        end)
      end
    end)
    it("accepts all valid approval policies", function()
      for _, pol in ipairs({ "prompt", "auto-deny", "auto-allow" }) do
        assert.has_no.errors(function()
          config.validate({ approval = { policy = pol } })
        end)
      end
    end)
  end)
end)
